### ISSUE TITLE
Fork RenderSync and fix refetches controller

### ISSUE THREAD

**Issue by rudresh4** [rudresh4/patchwork#85]
- refetches_controller uses before_filter which is meant for rails 4. Since app relies on rails 5, need to update render-sync dependency:

```
/opt/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/render_sync-0.5.0/app/controllers/sync/refetches_controller.rb:3:in `<class:RefetchesController>': undefined method `before_filter' for RenderSync::RefetchesController:Class (NoMethodError)
Did you mean?  before_action
        from /opt/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/render_sync-0.5.0/app/controllers/sync/refetches_controller.rb:1:in `<top (required)>'
```

**Comment by rudresh4** [comment]
Forked: c3f1625bee0b35604693ab24c35f5b4259a90c5e
Deployment fixed: ef2a02c6a5dd6d296e9c0c2d21b5863af02af4e5
